config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  resources :projects do
    resources :tasks
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root to: 'projects#index'
    end

    unauthenticated do
      root to: 'home#index', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :project_users
  has_many :users, through: :project_users

  has_many :tasks, dependent: :destroy

  def author(user)
    project_users.where(user: user)
  end
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  has_many :project_users
  has_many :projects, through: :project_users

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = Task.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        (@project.users.uniq - [current_user]).each do |user|
          ProjectMailer.with(project: @project, user: user, author: current_user).user_added_to_project.deliver_later
        end

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, user_ids: [])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end



  # GET /tasks/1/edit
  def edit
  end

  # POST /ta
  # POST /tasks.json
  def create
    @task = @project.tasks.create(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project), notice: 'Task was successfully created.' }
      else
        format.html { redirect_to project_path(@project) }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task = @project.tasks.find(params[:task][:id])

    respond_to do |format|
      if params[:task][:complete] == true
        @task.update(complete: true)
      else
        @task.update(complete: false)
      end


      if @task.update(task_params)
        format.json { render :show, status: :ok, location: project_path(@project) }
      else
        format.html { redirect_to project_path(@project) }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Task was successfully destroyed.' }
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:body, :project_id, :complete, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1 class="semibold text-2xl">Welcome to <%= Rails.configuration.application_name %></h1>
<p class="lead">Use this starting point as a way to quickly set up a new project by generating files, installing gems, and more.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="bg-white">

    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div class="bg-red-500">
          <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
        </div>
      <% end %>
      <% if type == "notice" %>
        <div class="bg-green-500">
          <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
        </div>
      <% end %>
    <% end %>

    <header class="mb-4">
      <nav class="flex flex-wrap items-center justify-between px-3 py-3 text-gray-700 bg-gray-100 border-b border-gray-400 lg:px-10">
        <div class="flex items-center mr-6 flex-no-shrink">
          <%= link_to root_path, class:"link text-xl tracking-tight font-semibold" do %>
            <h1 class="title is-5"><%= Rails.configuration.application_name %></h1>
          <% end  %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border border-gray-500 rounded text-grey hover:text-gray-600 hover:border-gray-600">
            <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
          <div class="lg:flex-grow">
            <%= link_to "Projects", projects_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
          </div>
          <div class="block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">

            <% if user_signed_in? %>
              <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-default mr-2 block" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-default mr-2 mb-2 lg:mr-2 lg:mb-0 block" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class:"btn btn-default mr-2 mb-2 lg:mr-2 lg:mb-0 block" %>
              <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default mr-2 block" %>
            <% end %>


          </div>
        </div>
      </nav>
    </header>

    <main class="px-4 lg:px-10">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="mb-6">
    <%= form.label :description, class: 'label' %>
    <%= form.text_area :description, class: 'input' %>
  </div>

  <div class="mb-6">
    <ul>
      <%= collection_check_boxes(:project, :user_ids, User.all, :id, :name) do |c| %>
        <li>
          <%= c.label {c.check_box(class: 'mx-6') + c.text} %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1 class="text-3xl font-bold">Projects</h1>

<div class="mb-10 grid grid-cols-12 gap-6">

  <% @projects.each do |project| %>
    <div class="p-6 border rounded shadow col-span-12 lg:col-span-3">
      <%= link_to project, class: "block" do %>
        <h3 class="mb-4 text-lg font-bold"><%= project.title %></h3>
        <p class="leading-snug text-gray-600"><%= truncate(project.description, length: 200) %></p>
      <% end %>
    </div>
  <% end %>
</div>
<div class="my-4">
  <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="max-w-4xl px-10 pt-10 pb-24 mx-auto mt-10 border rounded shadow-lg">
  <div class="flex justify-between flex-wrapitems-center">
    <h1 class="mb-4 text-4xl font-bold"><%= @project.title %></h1>
    <% if @project.author(current_user) %>
      <%= link_to 'Edit Project', edit_project_path(@project), class: "underline" %>
    <% end %>
   </div>


  <div class="text-lg font-light leading-relaxed text-gray-600">
    <p class="font-bold text-gray-900">
      Description
    </p>
    <%= @project.description %>
  </div>

  <h3 class="pb-3 my-6 text-2xl font-bold border-b">Tasks</h3>

  <% if @project.users.any? %>
    <h3 class="pb-3 my-6 text-2xl font-bold border-b">
    Collaborators
    </h3>
  <% end %>


  <ul id="<%= dom_id(@project) %>_tasks" 
      class="mb-6 leading-relaxed" 
      data-controller="tasks">

    <%= render @project.tasks %>
  </ul>



  <%= render 'tasks/form', task: @task %>



</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @project, task ], local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :body, 'Add a task', class: 'label' %>
    <%= form.text_area :body, class: 'input' %>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-default' %>
  </div>
<% end %>
</div>

app/views/tasks/_task.html.erb
<li>
  <label for="task_<%= task.id %>" 
         data-action="change->tasks#toggleComplete" 
         data-task-url="<%= project_task_url(task.project, task) %>" 
         data-task-id="<%= task.id %>" 
         class="<%= "completed" if task.complete? %>">

    <input type="checkbox" id="task_<%= task.id %>">
    <%= task.body %>
  </label>
</li>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Project</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.body %></td>
        <td><%= task.project_id %></td>
        <td><%= task.complete %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @task.body %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>